namespace Harlinn.MSSql.Tool.CodeGenerators.CSharp
{
    public class CSharpKeyWords : HashSet<string>
    {
        public CSharpKeyWords()
        {
            Add("abstract");
            Add("as");
            Add("base");
            Add("bool");
            Add("break");
            Add("byte");
            Add("case");
            Add("catch");
            Add("char");
            Add("checked");
            Add("class");
            Add("const");
            Add("continue");
            Add("decimal");
            Add("default");
            Add("delegate");
            Add("do");
            Add("double");
            Add("else");
            Add("enum");
            Add("event");
            Add("explicit");
            Add("extern");
            Add("false");
            Add("finally");
            Add("fixed");
            Add("float");
            Add("for");
            Add("foreach");
            Add("goto");
            Add("if");
            Add("implicit");
            Add("in");
            Add("int");
            Add("interface");
            Add("internal");
            Add("is");
            Add("lock");
            Add("long");
            Add("namespace");
            Add("new");
            Add("null");
            Add("object");
            Add("operator");
            Add("out");
            Add("override");
            Add("params");
            Add("private");
            Add("protected");
            Add("public");
            Add("readonly");
            Add("ref");
            Add("return");
            Add("sbyte");
            Add("sealed");
            Add("short");
            Add("sizeof");
            Add("stackalloc");
            Add("static");
            Add("string");
            Add("struct");
            Add("switch");
            Add("this");
            Add("throw");
            Add("true");
            Add("try");
            Add("typeof");
            Add("uint");
            Add("ulong");
            Add("unchecked");
            Add("unsafe");
            Add("ushort");
            Add("using");
            Add("virtual");
            Add("void");
            Add("volatile");
            Add("while");
        }
    }


}
