/*
    Copyright 2024-2026 Espen Harlinn
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
 
        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
#pragma once
#ifndef HARLINN_MATH_INTERNAL_OPENLIBM_CONSTEXPR_MATH_H_
#define HARLINN_MATH_INTERNAL_OPENLIBM_CONSTEXPR_MATH_H_

#include "openlibm.h"

#include "k_cos.inl"
#include "k_cosf.inl"
#include "k_exp.inl"
#include "k_expf.inl"
#include "k_rem_pio2.inl"
#include "k_sin.inl"
#include "k_sinf.inl"
#include "k_tan.inl"
#include "k_tanf.inl"

#include "e_acos.inl"
#include "e_acosf.inl"
#include "e_acosh.inl"
#include "e_acoshf.inl"
#include "e_asin.inl"
#include "e_asinf.inl"
#include "e_atan2.inl"
#include "e_atan2f.inl"
#include "e_atanh.inl"
#include "e_atanhf.inl"
#include "e_cosh.inl"
#include "e_coshf.inl"
#include "e_exp.inl"
#include "e_expf.inl"
#include "e_fmod.inl"
#include "e_fmodf.inl"
#include "e_hypot.inl"
#include "e_hypotf.inl"
#include "e_j0.inl"
#include "e_j0f.inl"
#include "e_j1.inl"
#include "e_j1f.inl"
#include "e_jn.inl"
#include "e_jnf.inl"
#include "e_lgamma.inl"
#include "e_lgamma_r.inl"
#include "e_lgammaf.inl"
#include "e_lgammaf_r.inl"
#include "e_log.inl"
#include "e_logf.inl"
#include "e_log2.inl"
#include "e_log2f.inl"
#include "e_log10.inl"
#include "e_log10f.inl"
#include "e_pow.inl"
#include "e_powf.inl"
#include "e_rem_pio2.inl"
#include "e_rem_pio2f.inl"
#include "e_remainder.inl"
#include "e_remainderf.inl"
#include "e_sinh.inl"
#include "e_sinhf.inl"
#include "e_sqrt.inl"
#include "e_sqrtf.inl"
#include "e_tgamma.inl"

#include "s_asinh.inl"
#include "s_asinhf.inl"
#include "s_atan.inl"
#include "s_atanf.inl"
//#include "s_cabs.inl"
//#include "s_cabsf.inl"
//#include "s_cacos.inl"
//#include "s_cacosf.inl"
//#include "s_cacosh.inl"
//#include "s_cacoshf.inl"
//#include "s_carg.inl"
//#include "s_cargf.inl"
//#include "s_casin.inl"
//#include "s_casinf.inl"
//#include "s_casinh.inl"
//#include "s_casinhf.inl"
//#include "s_catan.inl"
//#include "s_catanf.inl"
//#include "s_catanh.inl"
//#include "s_catanhf.inl"
#include "s_cbrt.inl"
#include "s_cbrtf.inl"
//#include "s_ccos.inl"
//#include "s_ccosf.inl"
//#include "s_ccosh.inl"
//#include "s_ccoshf.inl"
#include "s_ceil.inl"
#include "s_ceilf.inl"
//#include "s_cexp.inl"
//#include "s_cexpf.inl"
//#include "s_cimag.inl"
//#include "s_cimagf.inl"
//#include "s_clog.inl"
//#include "s_clogf.inl"
//#include "s_conj.inl"
//#include "s_conjf.inl"
#include "s_copysign.inl"
#include "s_copysignf.inl"
#include "s_cos.inl"
#include "s_cosf.inl"
//#include "s_cpow.inl"
//#include "s_cpowf.inl"
//#include "s_cproj.inl"
//#include "s_cprojf.inl"
//#include "s_creal.inl"
//#include "s_crealf.inl"
//#include "s_csin.inl"
//#include "s_csinf.inl"
//#include "s_csinh.inl"
//#include "s_csinhf.inl"
//#include "s_csqrt.inl"
//#include "s_csqrtf.inl"
//#include "s_ctan.inl"
//#include "s_ctanf.inl"
//#include "s_ctanh.inl"
//#include "s_ctanhf.inl"
#include "s_erf.inl"
#include "s_erff.inl"
#include "s_exp2.inl"
#include "s_exp2f.inl"
#include "s_expm1.inl"
#include "s_expm1f.inl"
#include "s_fabs.inl"
#include "s_fabsf.inl"
#include "s_fdim.inl"
#include "s_floor.inl"
#include "s_floorf.inl"
//#include "s_fma.inl"
//#include "s_fmaf.inl"
#include "s_fmax.inl"
#include "s_fmaxf.inl"
#include "s_fmin.inl"
#include "s_fminf.inl"
#include "s_fpclassify.inl"
#include "s_frexp.inl"
#include "s_frexpf.inl"
#include "s_ilogb.inl"
#include "s_ilogbf.inl"
#include "s_isfinite.inl"
#include "s_isinf.inl"
#include "s_isnan.inl"
#include "s_isnormal.inl"
#include "s_llrint.inl"
#include "s_llrintf.inl"
#include "s_llround.inl"
#include "s_llroundf.inl"
#include "s_log1p.inl"
#include "s_log1pf.inl"
#include "s_logb.inl"
#include "s_logbf.inl"
#include "s_lrint.inl"
#include "s_lrintf.inl"
#include "s_lround.inl"
#include "s_lroundf.inl"
#include "s_modf.inl"
#include "s_modff.inl"
#include "s_nan.inl"
#include "s_nearbyint.inl"
#include "s_nextafter.inl"
#include "s_nextafterf.inl"
#include "s_nexttoward.inl"
#include "s_nexttowardf.inl"
#include "s_remquo.inl"
#include "s_remquof.inl"
#include "s_rint.inl"
#include "s_rintf.inl"
#include "s_round.inl"
#include "s_roundf.inl"
#include "s_scalbln.inl"
#include "s_scalbn.inl"
#include "s_scalbnf.inl"
#include "s_signbit.inl"
//#include "s_signgam.inl"
#include "s_sin.inl"
#include "s_sinf.inl"
#include "s_sincos.inl"
#include "s_sincosf.inl"
#include "s_tan.inl"
#include "s_tanf.inl"
#include "s_tanh.inl"
#include "s_tanhf.inl"
#include "s_tgammaf.inl"
#include "s_trunc.inl"
#include "s_truncf.inl"

#endif
