/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_harlinn_common_platform_Kernel32 */

#ifndef _Included_com_harlinn_common_platform_Kernel32
#define _Included_com_harlinn_common_platform_Kernel32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_harlinn_common_platform_Kernel32
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_harlinn_common_platform_Kernel32_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_harlinn_common_platform_Kernel32
 * Method:    GetErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_harlinn_common_platform_Kernel32_GetErrorMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_harlinn_common_platform_Kernel32
 * Method:    GetSystemTimePreciseAsFileTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_harlinn_common_platform_Kernel32_GetSystemTimePreciseAsFileTime
  (JNIEnv *, jclass);

/*
 * Class:     com_harlinn_common_platform_Kernel32
 * Method:    FileTimeToLocalFileTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_harlinn_common_platform_Kernel32_FileTimeToLocalFileTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_harlinn_common_platform_Kernel32
 * Method:    LocalFileTimeToFileTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_harlinn_common_platform_Kernel32_LocalFileTimeToFileTime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
